version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@github/spark"
        reason: "This is a local workspace package"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      radix:
        patterns:
          - "@radix-ui/*"
      tailwind:
        patterns:
          - "tailwind*"
          - "@tailwindcss/*"
      dev-tools:
        patterns:
          - "eslint*"
          - "typescript*"
          - "vite*"
          - "@vitejs/*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
